  - name: check nginx is running
    shell: service nginx status
    become: yes
    
  - name: get start time
    shell: |  
      echo Now: `date`
      pid=`ps aux | grep nginx | grep -v grep | head -1 | awk '{print $2}'`
      stat -c %z /proc/$pid
    become: yes
