- name: nginx
  yum: name=nginx state=installed
  become: yes

- name: config nginx
  template: src=vhosts.j2 dest=/etc/nginx/conf.d/vhosts.conf
  become: yes
  notify: restart nginx

- name: run nginx
  service: name=nginx state=started
  become: yes
