- name: install java tomcat nginx
  hosts: webservers
  roles:
  - java
  - tomcat
  - nginx

- name: check java tomcat nginx
  hosts: webservers
  roles:
  - java_test
  - tomcat_test
  - nginx_test

- name: is available from local_cm
  hosts: local_cm
  tasks:
  - name: check tomcat availability from host
    shell: |
     curl -sL -w %{http_code} http://192.168.33.10 -o /dev/null
     if [ $? -eq 0 ]; then
      echo '. curl Success'
     else
      echo '. curl Fail'
     fi
    register: result

  - name: debug
    debug:
      msg: "Curl status: {{result.stdout}}"

