- name: node
  hosts: localhost
  
  vars:
    state: started

  # tasks:
  # - name: vagrant provision
  #   prov: path=Vagrantfile state={{state}}
  #   register: vagrant_vars
  # - debug: msg={{vagrant_vars}}
  # - add_host:
  #     name: websvr
  #     ansible_host: "{{vagrant_vars.ip}}"
  #     ansible_port: "{{vagrant_vars.port}}"
  #     ansible_connection: ssh 
  #     ansible_user: "{{vagrant_vars.user}}"
  #     ansible_ssh_private_key_file: "{{vagrant_vars.key}}"
  #   when: vagrant_vars.status == "running"

- name: tomcat site
  hosts: websvr
  roles:
    - { role: java}
    - { role: tomcat}
    - { role: nginx} 
    - { role: java_test}
    - { role: tomcat_test}
    - { role: nginx_test}
    - { role: roles/deploy }


- name: deploy app
  hosts: localhost
  tasks:
  - deploy: 
  #  war=~/cm/ansible/day-4/hello-war/target/mnt-lab.war username=deploy password=123
  tags:
      - deploy_war

### Deploy
# echo $(date +"%T") $(hostname) $(whoami) > src/main/resources/build-info.txt
# mvn clean package -DbuildNumber=5
# curl --silent -T "/home/student/cm/ansible/day-4/hello-war/target/mnt-lab.war" -u deploy:123 "127.0.0.1:8080/manager/text/deploy?path=/mnt-lab&update=true"
# curl 127.0.0.1:8080
