- name: Local
  hosts: local

  tasks:

  - name: Getting vagrant stats
    vagrant:
      path: "/home/student/cm/ansible/day-3/"
      state: started 
    register: vagrant_result

  - debug:
       msg: "{{vagrant_result.ip}}"
  - debug:
       msg: "{{vagrant_result.port}}"


  - add_host:
       name: vagrant
       ansible_port: "{{vagrant_result.port}}"
       ansible_host: "{{vagrant_result.ip}}" #192.168.100.100
       ansible_connection: ssh
       ansible_user: vagrant
       ansible_ssh_private_key_file: ".vagrant/machines/default/virtualbox/private_key"

- name: Installation
  hosts: vagrant

  vars:
    java_version: 1.7.0

  roles:
    - java
    - tomcat
    - nginx

- name: Verification
  hosts: vagrant

  vars:
    java_version: 1.7.0

  roles:
    - java_test
    - tomcat_test
    - nginx_test

- name: localhost curlык
  hosts: local

  tasks:
  
  - name: Checking if tomcat is availible
    uri:
      url: http://192.168.100.100/
      status_code: 200
 
