- name: Installing nginx
  become: yes
  yum:
    name: nginx
    state: present

- name: Copying nginx config
  become: yes
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
     - Restart Nginx

- name: Starting Nginx
  become: yes
  service:
    name:  nginx
    state: started
