- hosts: localhost
  connection: local

  vars:
    mongodb_version: 3
    mongo_src:
    - mongodb-linux-x86_64-rhel62-3.4.1
    - mongodb-linux-x86_64-rhel70-3.4.1
    - mongodb-linux-x86_64-rhel55-3.2.11
    - mongodb-linux-x86_64-rhel64-3.2.11
    - mongodb-linux-x86_64-rhel70-3.2.17
    - mongodb-linux-x86_64-rhel55-3.0.14
    - mongodb-linux-x86_64-rhel64-3.0.14
    - mongodb-linux-x86_64-rhel70-3.0.14

  tasks:
  - debug: msg={{ mongo_src | get_mongo_src(ansible_os_family, ansible_distribution_major_version, mongodb_version) }}
