- name: Getting java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g' | cut -c-5
  register: java_version_shell
  changed_when: false

- name: Debug java version
  debug:
    msg: "{{java_version_shell.stdout}}"

- name: Checking if java version > {{java_version}}
  assert:
    that: 
      - java_version_shell.stdout | version_compare('{{java_version}}', '>=')
    msg: Java fail


